name: "Github Release"
author: "Lars Gohr"
branding:
  icon: "git-branch"
  color: "gray-dark"
description: "Publish Github releases from an action"

inputs:
  title:
    description: "The name of the release to publish"
    required: true

runs:
  using: 'composite'
  steps:      
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        INPUT_TITLE: ${{ inputs.title }}
