name: "Github Release"
author: "Lars Gohr"
branding:
  icon: "git-branch"
  color: "gray-dark"
description: "Publish Github releases from an action"

inputs:
  tag:
    description: "The tag of the release to publish"
    required: false
  title:
    description: "The title of the release to publish"
    required: true
  body:
    description: "The body of the release to publish"
    required: false

runs:
  using: 'composite'
  steps:      
    - run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        INPUT_TAG: ${{ inputs.tag }}
        INPUT_TITLE: ${{ inputs.title }}
        INPUT_BODY: ${{ inputs.body }}
